// Offline generator: exercises the same preparation function as the CRE handler.
import { getContractAddress } from "viem";
import config from "../fixtures/config.json";
import evidence from "../fixtures/observations.json";
import { prepareSettlement } from "../src/settlement";

const deployer = "0x0000000000000000000000000000000000c0ffee";
const pool = getContractAddress({ from: deployer, nonce: 1n }).toLowerCase();
const observedAt = 1700000030;
const reports = Array.from({ length: 4 }, (_, state) => prepareSettlement({ ...config, pool }, {
  ...evidence,
  observations: evidence.observations.map((observation, bit) => ({
    ...observation, outcome: Boolean(state & (1 << bit)),
  })),
}, observedAt));

const content = `// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

// Generated by workflows/cre/scripts/settlement-fixtures.ts; do not edit.
// Synthetic fixtures only. The deployer/nonce are local test context, not a live deployment.
library CreWorkflowFixtures {
    address internal constant DEPLOYER = address(0xC0FFEE);
    address internal constant POOL = address(bytes20(hex"${pool.slice(2)}"));
    uint256 internal constant CHAIN_ID = ${config.chainId};
    uint64 internal constant CLOSES_AT = ${config.closesAt};
    uint64 internal constant OBSERVED_AT = ${observedAt};
    bytes32 internal constant RULES = ${reports[0].rulesHash};

    function report(uint8 state) internal pure returns (bytes memory) {
${reports.map((report, state) => `        if (state == ${state}) {
            return hex"${report.unsignedReport.slice(2)}";
        }`).join("\n")}
        revert("unknown fixture state");
    }
}
`;

const path = new URL("../../../contracts/test/helpers/CreWorkflowFixtures.sol", import.meta.url);
if (Bun.argv.includes("--check")) {
  const actual = await Bun.file(path).text();
  if (actual.replaceAll("\r\n", "\n") !== content) throw new Error("CRE Solidity fixtures are stale; run bun run fixtures");
} else {
  await Bun.write(path, content);
}
