// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
// Generated by scripts/factored_log_fixtures.py; do not edit.
import {FactoredLogMath as M} from "../src/FactoredLogMath.sol";
import {QuoteMath} from "../src/QuoteMath.sol";

contract FactoredLogFixturesTest {
    function test_pair_0() public pure {
        M.LogBounds memory result = M.logSumExp(M.LogBounds(0, 0), M.LogBounds(0, 0));
        assert(result.lower <= 693147180559945309 && result.upper >= 693147180559945310);
    }

    function test_pair_1() public pure {
        M.LogBounds memory result = M.logSumExp(M.LogBounds(0, 0), M.LogBounds(1, 1));
        assert(result.lower <= 693147180559945309 && result.upper >= 693147180559945310);
    }

    function test_pair_2() public pure {
        M.LogBounds memory result = M.logSumExp(
            M.LogBounds(1000000000000000000, 1000000000000000000), M.LogBounds(1000000000000000001, 1000000000000000001)
        );
        assert(result.lower <= 1693147180559945309 && result.upper >= 1693147180559945310);
    }

    function test_pair_3() public pure {
        M.LogBounds memory result =
            M.logSumExp(M.LogBounds(41000000000000000000, 41000000000000000000), M.LogBounds(0, 0));
        assert(result.lower <= 41000000000000000001 && result.upper >= 41000000000000000002);
    }

    function test_pair_4() public pure {
        M.LogBounds memory result =
            M.logSumExp(M.LogBounds(100000000000000000000, 100000000000000000000), M.LogBounds(0, 0));
        assert(result.lower <= 100000000000000000000 && result.upper >= 100000000000000000001);
    }

    function test_pair_5() public pure {
        M.LogBounds memory result =
            M.logSumExp(M.LogBounds(100000000000000000001, 100000000000000000001), M.LogBounds(0, 0));
        assert(result.lower <= 100000000000000000001 && result.upper >= 100000000000000000002);
    }

    function test_pair_6() public pure {
        M.LogBounds memory result =
            M.logSumExp(M.LogBounds(127000000000000000000, 127000000000000000000), M.LogBounds(0, 0));
        assert(result.lower <= 127000000000000000000 && result.upper >= 127000000000000000001);
    }

    function test_pair_7() public pure {
        M.LogBounds memory result = M.logSumExp(
            M.LogBounds(120000000000000000000, 120000000000000000000),
            M.LogBounds(120000000000000000000, 120000000000000000000)
        );
        assert(result.lower <= 120693147180559945309 && result.upper >= 120693147180559945310);
    }

    function test_pair_8() public pure {
        M.LogBounds memory result = M.logSumExp(
            M.LogBounds(28000000000000000000, 28000000000000000000),
            M.LogBounds(127000000000000000000, 127000000000000000000)
        );
        assert(result.lower <= 127000000000000000000 && result.upper >= 127000000000000000001);
    }

    function test_cost_0() public pure {
        M.LogBounds memory left = M.logSumExp(M.normalize(0, 1000000000000), M.normalize(1, 1000000000000));
        M.LogBounds memory right =
            M.logSumExp(M.normalize(333333333333, 1000000000000), M.normalize(100000000000000, 1000000000000));
        QuoteMath.CostBounds memory result = M.cost(M.logSumExp(left, right), 1000000000000);
        assert(result.lowerWad <= 100000000000000 && result.upperWad >= 100000000000001);
    }

    function test_cost_1() public pure {
        M.LogBounds memory left = M.logSumExp(M.normalize(0, 3000000000000000001), M.normalize(1, 3000000000000000001));
        M.LogBounds memory right = M.logSumExp(
            M.normalize(1000000000000000000, 3000000000000000001),
            M.normalize(300000000000000000100, 3000000000000000001)
        );
        QuoteMath.CostBounds memory result = M.cost(M.logSumExp(left, right), 3000000000000000001);
        assert(result.lowerWad <= 300000000000000000100 && result.upperWad >= 300000000000000000101);
    }

    function test_cost_2() public pure {
        M.LogBounds memory left =
            M.logSumExp(M.normalize(0, 1000000000000000000000000000), M.normalize(1, 1000000000000000000000000000));
        M.LogBounds memory right = M.logSumExp(
            M.normalize(333333333333333333333333333, 1000000000000000000000000000),
            M.normalize(100000000000000000000000000000, 1000000000000000000000000000)
        );
        QuoteMath.CostBounds memory result = M.cost(M.logSumExp(left, right), 1000000000000000000000000000);
        assert(result.lowerWad <= 100000000000000000000000000000 && result.upperWad >= 100000000000000000000000000001);
    }

    function test_chain_32() public pure {
        M.LogBounds memory zero = M.LogBounds(0, 0);
        M.LogBounds memory one = zero;
        M.LogBounds memory edge = M.normalize(1e18, 10e18);
        for (uint256 i; i < 31; i++) {
            M.LogBounds memory nextZero = M.logSumExp(zero, M.add(one, edge));
            one = M.logSumExp(M.add(zero, edge), one);
            zero = nextZero;
        }
        QuoteMath.CostBounds memory result = M.cost(M.logSumExp(zero, one), 10e18);
        assert(result.lowerWad <= 237694436428406430491 && result.upperWad >= 237694436428406430492);
        assert(result.upperWad - result.lowerWad <= 2 * (64 + 32 * 2562) * 10 + 2);
    }
}
