// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
// Generated by scripts/factored_cost_fixtures.py; do not edit.
import {FactoredCost as F} from "../src/FactoredCost.sol";
import {QuoteMath} from "../src/QuoteMath.sol";

contract FactoredCostFixturesTest {
    function test_graph_0() public pure {
        check(3, 1000000000000, hex"0001060507", hex"000102", 1, 12075395008316, 12075395008317, 11400000000000);
    }

    function test_graph_1() public pure {
        check(
            3,
            3000000000000000001,
            hex"0001060507",
            hex"000102",
            1,
            36226185024949179720,
            36226185024949179721,
            34200000000000000010
        );
    }

    function test_graph_2() public pure {
        check(
            3,
            1000000000000000000000000000,
            hex"0001060507",
            hex"000102",
            1,
            12075395008316393236821115536,
            12075395008316393236821115537,
            11400000000000000000000000000
        );
    }

    function test_graph_3() public pure {
        check(3, 1000000000000, hex"0001060507", hex"000201", 2, 11878140305930, 11878140305931, 11500000000000);
    }

    function test_graph_4() public pure {
        check(
            3,
            3000000000000000001,
            hex"0001060507",
            hex"000201",
            2,
            35634420917792076884,
            35634420917792076885,
            34500000000000000009
        );
    }

    function test_graph_5() public pure {
        check(
            3,
            1000000000000000000000000000,
            hex"0001060507",
            hex"000201",
            2,
            11878140305930692291815337884,
            11878140305930692291815337885,
            11500000000000000000000000000
        );
    }

    function test_graph_6() public pure {
        check(3, 1000000000000, hex"0001060507", hex"010002", 3, 12147184821611, 12147184821612, 12000000000000);
    }

    function test_graph_7() public pure {
        check(
            3,
            3000000000000000001,
            hex"0001060507",
            hex"010002",
            3,
            36441554464833227938,
            36441554464833227939,
            36000000000000000010
        );
    }

    function test_graph_8() public pure {
        check(
            3,
            1000000000000000000000000000,
            hex"0001060507",
            hex"010002",
            3,
            12147184821611075976171645998,
            12147184821611075976171645999,
            12000000000000000000000000000
        );
    }

    function test_graph_9() public pure {
        check(3, 1000000000000, hex"0001060507", hex"010200", 4, 12647184821611, 12647184821612, 12500000000000);
    }

    function test_graph_10() public pure {
        check(
            3,
            3000000000000000001,
            hex"0001060507",
            hex"010200",
            4,
            37941554464833227938,
            37941554464833227939,
            37500000000000000010
        );
    }

    function test_graph_11() public pure {
        check(
            3,
            1000000000000000000000000000,
            hex"0001060507",
            hex"010200",
            4,
            12647184821611075976171645998,
            12647184821611075976171645999,
            12500000000000000000000000000
        );
    }

    function test_graph_12() public pure {
        check(3, 1000000000000, hex"0001060507", hex"020001", 5, 13147184821611, 13147184821612, 13000000000000);
    }

    function test_graph_13() public pure {
        check(
            3,
            3000000000000000001,
            hex"0001060507",
            hex"020001",
            5,
            39441554464833227938,
            39441554464833227939,
            39000000000000000010
        );
    }

    function test_graph_14() public pure {
        check(
            3,
            1000000000000000000000000000,
            hex"0001060507",
            hex"020001",
            5,
            13147184821611075976171645998,
            13147184821611075976171645999,
            13000000000000000000000000000
        );
    }

    function test_graph_15() public pure {
        check(3, 1000000000000, hex"0001060507", hex"020100", 6, 13645072124957, 13645072124958, 13500000000000);
    }

    function test_graph_16() public pure {
        check(
            3,
            3000000000000000001,
            hex"0001060507",
            hex"020100",
            6,
            40935216374871273768,
            40935216374871273769,
            40500000000000000012
        );
    }

    function test_graph_17() public pure {
        check(
            3,
            1000000000000000000000000000,
            hex"0001060507",
            hex"020100",
            6,
            13645072124957091252086034030,
            13645072124957091252086034031,
            13500000000000000000000000000
        );
    }

    function test_graph_18() public pure {
        check(
            4,
            10000000000000000000,
            hex"03060c09",
            hex"00010203",
            9,
            129353215370280996963,
            129353215370280996964,
            117000000000000000000
        );
    }

    function test_graph_19() public pure {
        check(
            6,
            10000000000000000000,
            hex"000528",
            hex"050301000204",
            7,
            102291241423332789746,
            102291241423332789747,
            81000000000000000000
        );
    }

    function test_graph_20() public pure {
        check(1, 1000000000000, hex"", hex"00", 0, 693147180559, 693147180560, 0);
    }

    function test_32_events_width_1() public pure {
        F.Factor[] memory factors = new F.Factor[](31);
        for (uint256 i; i < 31; i++) {
            factors[i].scope = uint32(3) << uint32(i % 31);
            factors[i].values = new uint256[](4);
            for (uint256 j; j < 4; j++) {
                factors[i].values[j] = ((j ^ (j >> 1) ^ (j >> 2)) & 1) * 1e18;
            }
        }
        uint8[] memory order = new uint8[](32);
        for (uint8 i; i < 32; i++) {
            order[i] = i;
        }
        assert(F.validate(32, 10e18, factors, order) == 1);
        QuoteMath.CostBounds memory result = F.bounds(32, 10e18, factors, order);
        assert(result.lowerWad <= 237694436428406430491 && result.upperWad >= 237694436428406430492);
        assert(result.upperWad - result.lowerWad <= 2 * (64 + 32 * 2562) * 10 + 2);
        assert(F.maxLiability(32, 10e18, factors, order) == 31e18);
    }

    function test_32_events_width_2() public pure {
        F.Factor[] memory factors = new F.Factor[](64);
        for (uint256 i; i < 64; i++) {
            factors[i].scope = uint32(7) << uint32(i % 30);
            factors[i].values = new uint256[](8);
            for (uint256 j; j < 8; j++) {
                factors[i].values[j] = ((j ^ (j >> 1) ^ (j >> 2)) & 1) * 1e18;
            }
        }
        uint8[] memory order = new uint8[](32);
        for (uint8 i; i < 32; i++) {
            order[i] = i;
        }
        assert(F.validate(32, 10e18, factors, order) == 2);
        QuoteMath.CostBounds memory result = F.bounds(32, 10e18, factors, order);
        assert(result.lowerWad <= 255553259429153869259 && result.upperWad >= 255553259429153869260);
        assert(result.upperWad - result.lowerWad <= 2 * (64 + 32 * 2562) * 10 + 2);
        assert(F.maxLiability(32, 10e18, factors, order) == 64e18);
    }

    function check(
        uint8 events,
        uint256 b,
        bytes memory scopes,
        bytes memory permutation,
        uint256 seed,
        uint256 lo,
        uint256 hi,
        uint256 maximum
    ) private pure {
        F.Factor[] memory factors = new F.Factor[](scopes.length);
        for (uint256 i; i < scopes.length; i++) {
            uint32 scope = uint8(scopes[i]);
            uint256 size;
            for (uint32 s = scope; s != 0; s &= s - 1) {
                size++;
            }
            factors[i].scope = scope;
            factors[i].values = new uint256[](1 << size);
            for (uint256 j; j < factors[i].values.length; j++) {
                factors[i].values[j] = ((seed + i * 7 + j * 13) % 43) * b / 10;
            }
        }
        uint8[] memory order = new uint8[](permutation.length);
        for (uint256 i; i < order.length; i++) {
            order[i] = uint8(permutation[i]);
        }
        QuoteMath.CostBounds memory result = F.bounds(events, b, factors, order);
        assert(result.lowerWad <= lo && result.upperWad >= hi);
        assert(F.maxLiability(events, b, factors, order) == maximum);
    }
}
