// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
// Generated by scripts/factored_quote_fixtures.py; do not edit.
import {FactoredQuote as Q} from "../src/FactoredQuote.sol";

contract FactoredQuoteFixturesTest {
    function test_quote_0_0() public pure {
        check(0, 3, 8, true, 3, 119);
    }

    function test_quote_0_1() public pure {
        check(0, 5, 14, true, 8, 120);
    }

    function test_quote_0_2() public pure {
        check(0, 5, 14, false, 7, 105);
    }

    function test_quote_0_3() public pure {
        check(0, 7, 85, true, 6, 117);
    }

    function test_quote_0_4() public pure {
        check(0, 7, 85, false, 4, 110);
    }

    function test_quote_0_5() public pure {
        check(0, 1, 2, false, 4, 107);
    }

    function test_quote_6_0() public pure {
        check(6, 3, 8, true, 2626209, 120500000);
    }

    function test_quote_6_1() public pure {
        check(6, 5, 14, true, 7622647, 120900000);
    }

    function test_quote_6_2() public pure {
        check(6, 5, 14, false, 7436736, 107000000);
    }

    function test_quote_6_3() public pure {
        check(6, 7, 85, true, 5054513, 118800000);
    }

    function test_quote_6_4() public pure {
        check(6, 7, 85, false, 4804665, 110900000);
    }

    function test_quote_6_5() public pure {
        check(6, 1, 2, false, 4945487, 108800000);
    }

    function test_quote_18_0() public pure {
        check(18, 3, 8, true, 2626208421259378674, 120500000000000000000);
    }

    function test_quote_18_1() public pure {
        check(18, 5, 14, true, 7622646207364114791, 120900000000000000000);
    }

    function test_quote_18_2() public pure {
        check(18, 5, 14, false, 7436736873442142805, 107000000000000000000);
    }

    function test_quote_18_3() public pure {
        check(18, 7, 85, true, 5054512052910181521, 118800000000000000000);
    }

    function test_quote_18_4() public pure {
        check(18, 7, 85, false, 4804665727424846356, 110900000000000000000);
    }

    function test_quote_18_5() public pure {
        check(18, 1, 2, false, 4945487947089818479, 108800000000000000000);
    }

    function check(uint8 decimals, uint32 scope, uint256 mask, bool isBuy, uint256 ideal, uint256 maximum)
        private
        pure
    {
        uint128 unit = uint128(10 ** uint256(decimals));
        Q.Market memory m;
        m.events = 3;
        m.decimals = decimals;
        m.liquidity = 100 * unit;
        m.order = new uint8[](3);
        m.order[0] = 2;
        m.order[1] = 0;
        m.order[2] = 1;
        m.factors = new Q.Factor[](5);
        uint32[5] memory scopes = [uint32(0), 1, 6, 5, 7];
        for (uint256 i; i < scopes.length; i++) {
            uint256 size;
            for (uint32 s = scopes[i]; s != 0; s &= s - 1) {
                size++;
            }
            m.factors[i].scope = scopes[i];
            m.factors[i].values = new uint128[](1 << size);
            for (uint256 j; j < m.factors[i].values.length; j++) {
                m.factors[i].values[j] = 20 * unit + uint128((i * 7 + j * 13) % 43) * unit / 10;
            }
        }
        Q.Quote memory result =
            isBuy ? Q.buy(m, scope, mask, 10 * unit, 10 * unit) : Q.sell(m, scope, mask, 10 * unit, 1);
        assert(result.maxLiabilityAfter == maximum);
        uint256 numerator = 2 * uint256(m.liquidity) * 82048;
        uint256 allowance = numerator / 1e18 + (numerator % 1e18 == 0 ? 0 : 1) + 3;
        if (isBuy) assert(result.collateral >= ideal && result.collateral - ideal <= allowance);
        else assert(result.collateral <= ideal && ideal - result.collateral <= allowance);
    }
}
