// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
// Generated by scripts/lmsr_quote_fixtures.py; do not edit.
import {LmsrQuote} from "../src/LmsrQuote.sol";

contract LmsrQuoteFixturesTest {
    function test_uniform_buy_6() public pure {
        uint128[] memory q = new uint128[](4);
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 8, 10000000, type(uint128).max);
        assert(result.collateral >= 2595302 && result.collateral <= 2595302 + 2);
    }

    function test_uniform_sell_6() public pure {
        uint128[] memory q = new uint128[](4);
        q[0] = 10000000;
        q[1] = 10000000;
        q[2] = 10000000;
        q[3] = 10000000;
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.sell(m, 8, 10000000, 0);
        assert(result.collateral <= 2407821 && result.collateral + 2 >= 2407821);
    }

    function test_correlated_buy_6() public pure {
        uint128[] memory q = new uint128[](4);
        q[0] = 60000000;
        q[1] = 10000000;
        q[2] = 10000000;
        q[3] = 60000000;
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 8, 10000000, type(uint128).max);
        assert(result.collateral >= 3220802 && result.collateral <= 3220802 + 2);
    }

    function test_correlated_sell_6() public pure {
        uint128[] memory q = new uint128[](4);
        q[0] = 60000000;
        q[1] = 10000000;
        q[2] = 10000000;
        q[3] = 60000000;
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.sell(m, 10, 10000000, 0);
        assert(result.collateral <= 4875052 && result.collateral + 2 >= 4875052);
    }

    function test_three_events_6() public pure {
        uint128[] memory q = new uint128[](8);
        q[0] = 1000000;
        q[1] = 2000000;
        q[2] = 3000000;
        q[3] = 4000000;
        q[4] = 5000000;
        q[5] = 6000000;
        q[6] = 7000000;
        q[7] = 8000000;
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 20000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 168, 2000000, type(uint128).max);
        assert(result.collateral >= 830016 && result.collateral <= 830016 + 2);
    }

    function test_small_trade_18() public pure {
        uint128[] memory q = new uint128[](4);
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000000000000000, 18);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 8, 100000000000, type(uint128).max);
        assert(result.collateral >= 25000000010 && result.collateral <= 25000000010 + 921605);
    }

    function test_rare_claim_6() public pure {
        uint128[] memory q = new uint128[](4);
        q[0] = 10000000000;
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 8, 10000000, type(uint128).max);
        assert(result.collateral >= 1 && result.collateral <= 1 + 2);
    }

    function test_likely_sell_6() public pure {
        uint128[] memory q = new uint128[](4);
        q[0] = 10000000000;
        q[1] = 10000000;
        q[2] = 10000000;
        q[3] = 10000000;
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000, 6);
        LmsrQuote.Quote memory result = LmsrQuote.sell(m, 1, 10000000, 0);
        assert(result.collateral <= 9999999 && result.collateral + 2 >= 9999999);
    }

    function test_uniform_buy_0() public pure {
        uint128[] memory q = new uint128[](4);
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100, 0);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 8, 10, type(uint128).max);
        assert(result.collateral >= 3 && result.collateral <= 3 + 2);
    }

    function test_uniform_buy_18() public pure {
        uint128[] memory q = new uint128[](4);
        LmsrQuote.Market memory m = LmsrQuote.Market(q, 100000000000000000000, 18);
        LmsrQuote.Quote memory result = LmsrQuote.buy(m, 8, 10000000000000000000, type(uint128).max);
        assert(result.collateral >= 2595301747695551717 && result.collateral <= 2595301747695551717 + 921605);
    }
}
