// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;
// Generated by scripts/quote_bounds_fixtures.py; do not edit.
import {QuoteMath} from "../src/QuoteMath.sol";

contract QuoteBoundsFixturesTest {
    function testFixture_uniform_buy() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(138629436111989061882, 138629436111989061885);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(141224737859684613598, 141224737859684613601);
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 0);
            assert(quote >= 3 && quote <= 3 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 6);
            assert(quote >= 2595302 && quote <= 2595302 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 18);
            assert(quote >= 2595301747695551717 && quote <= 2595301747695551717 + 4);
        }
    }

    function testFixture_uniform_sell() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(148629436111989061882, 148629436111989061885);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(146221614811914532572, 146221614811914532575);
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 0);
            assert(quote <= 2 && quote + 4 >= 2);
        }
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 6);
            assert(quote <= 2407821 && quote + 4 >= 2407821);
        }
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 18);
            assert(quote <= 2407821300074529310 && quote + 4 >= 2407821300074529310);
        }
    }

    function testFixture_correlated_buy() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(176722416474005199028, 176722416474005199031);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(179943218253792380275, 179943218253792380278);
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 0);
            assert(quote >= 4 && quote <= 4 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 6);
            assert(quote >= 3220802 && quote <= 3220802 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 18);
            assert(quote >= 3220801779787181248 && quote <= 3220801779787181248 + 4);
        }
    }

    function testFixture_correlated_sell() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(176722416474005199028, 176722416474005199031);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(171847364425367757569, 171847364425367757572);
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 0);
            assert(quote <= 4 && quote + 4 >= 4);
        }
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 6);
            assert(quote <= 4875052 && quote + 4 >= 4875052);
        }
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 18);
            assert(quote <= 4875052048637441458 && quote + 4 >= 4875052048637441458);
        }
    }

    function testFixture_three_events() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(46219903549368980572, 46219903549368980575);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(47049919242358167387, 47049919242358167390);
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 0);
            assert(quote >= 1 && quote <= 1 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 6);
            assert(quote >= 830016 && quote <= 830016 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 18);
            assert(quote >= 830015692989186815 && quote <= 830015692989186815 + 4);
        }
    }

    function testFixture_small_trade() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(138629436111989061882, 138629436111989061885);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(138629436136989061891, 138629436136989061894);
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 0);
            assert(quote >= 1 && quote <= 1 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 6);
            assert(quote >= 1 && quote <= 1 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 18);
            assert(quote >= 25000000010 && quote <= 25000000010 + 4);
        }
    }

    function testFixture_rare_claim() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(9999999999999999999999, 10000000000000000000002);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(9999999999999999999999, 10000000000000000000002);
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 0);
            assert(quote >= 1 && quote <= 1 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 6);
            assert(quote >= 1 && quote <= 1 + 4);
        }
        {
            uint128 quote = QuoteMath.buyFromBounds(a, b, 18);
            assert(quote >= 1 && quote <= 1 + 4);
        }
    }

    function testFixture_likely_sell() public pure {
        QuoteMath.CostBounds memory a = QuoteMath.CostBounds(9999999999999999999999, 10000000000000000000002);
        QuoteMath.CostBounds memory b = QuoteMath.CostBounds(9989999999999999999999, 9990000000000000000002);
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 0);
            assert(quote <= 9 && quote + 4 >= 9);
        }
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 6);
            assert(quote <= 9999999 && quote + 4 >= 9999999);
        }
        {
            uint128 quote = QuoteMath.sellFromBounds(a, b, 18);
            assert(quote <= 9999999999999999999 && quote + 4 >= 9999999999999999999);
        }
    }
}
