import type { Abi } from 'viem';
export const pilotCash: `0x${string}`;
export const resolverAbi: Abi;
export const pilotPoolAbi: Abi;
export const pilotCashAbi: Abi;
export function evidenceURI(value: unknown): boolean;
export function validClaim(scope: number, mask: bigint, count: number): boolean;
export type PilotManifest = { status: string; pool: `0x${string}`; resolver: `0x${string}`; rulesHash: string; draftHash: string;
  verifiedBlock: string; verifiedBlockHash: string; codeHashes: Record<string,string>;
  publication: {creator: string; mode?: 'official-releases'|'rehearsal'|'ethereum-activity'; reviewerControl?: 'independent-panel'|'single-operator'; bondAtoms: string; assertionPeriod: number; challengePeriod: number; votingPeriod: number;
    reviewers: {name:string;address:string}[];
    draft: {title:string; closesAt:number; exceptionPolicy:string; disputePolicy:string;
      events:{id:string;question:string;yesRule:string;noRule:string;observationStartsAt:number;observationEndsAt:number;source:{referenceUrl:string;recordId:string}}[]}}};
export function pilotCall(input: {to: string; data: string; manifest: PilotManifest}): null | {abi: Abi;name:string;args: readonly unknown[]};
