"""Generate independent 80/120-digit fixtures for the factored interval kernel."""
from decimal import Decimal as D, ROUND_CEILING, ROUND_FLOOR, localcontext
from math import factorial
from pathlib import Path

U = 10**18


def bracket(calculate, precision):
    with localcontext() as context:
        context.prec = precision
        result = calculate()
        return (int(result.to_integral_value(rounding=ROUND_FLOOR)),
                int(result.to_integral_value(rounding=ROUND_CEILING)))


def stable(calculate):
    result = bracket(calculate, 80)
    assert result == bracket(calculate, 120)
    return result


def render():
    # Exact integer certificate: exp(100) > 100^16/16! > U.
    assert 100**16 > U * factorial(16)
    lines = ['// SPDX-License-Identifier: UNLICENSED', 'pragma solidity 0.8.28;',
             '// Generated by scripts/factored_log_fixtures.py; do not edit.',
             'import {FactoredLogMath as M} from "../src/FactoredLogMath.sol";',
             'import {QuoteMath} from "../src/QuoteMath.sol";',
             'contract FactoredLogFixturesTest {']
    pairs = [(0, 0), (0, 1), (U, U + 1), (41*U, 0), (100*U, 0),
             (100*U + 1, 0), (127*U, 0), (120*U, 120*U), (28*U, 127*U)]
    for i, (a, b) in enumerate(pairs):
        lo, hi = stable(lambda: ((D(a)/U).exp() + (D(b)/U).exp()).ln() * U)
        lines += [f'    function test_pair_{i}() public pure {{',
                  f'        M.LogBounds memory result = M.logSumExp(M.LogBounds({a}, {a}), M.LogBounds({b}, {b}));',
                  f'        assert(result.lower <= {lo} && result.upper >= {hi});', '    }']
    # Independent direct four-state costs check normalization, repeated reductions and b scaling.
    for i, b in enumerate([10**12, 3*U + 1, 10**27]):
        q = [0, 1, b // 3, 100*b]
        lo, hi = stable(lambda: sum((D(x)/b).exp() for x in q).ln() * b)
        lines += [f'    function test_cost_{i}() public pure {{',
                  f'        M.LogBounds memory left = M.logSumExp(M.normalize({q[0]}, {b}), M.normalize({q[1]}, {b}));',
                  f'        M.LogBounds memory right = M.logSumExp(M.normalize({q[2]}, {b}), M.normalize({q[3]}, {b}));',
                  f'        QuoteMath.CostBounds memory result = M.cost(M.logSumExp(left, right), {b});',
                  f'        assert(result.lowerWad <= {lo} && result.upperWad >= {hi});', '    }']
    lo, hi = stable(lambda: (D(2).ln() + 31 * (1 + D("0.1").exp()).ln()) * 10 * U)
    lines += ['    function test_chain_32() public pure {',
              '        M.LogBounds memory zero = M.LogBounds(0, 0);',
              '        M.LogBounds memory one = zero;',
              '        M.LogBounds memory edge = M.normalize(1e18, 10e18);',
              '        for (uint256 i; i < 31; i++) {',
              '            M.LogBounds memory nextZero = M.logSumExp(zero, M.add(one, edge));',
              '            one = M.logSumExp(M.add(zero, edge), one);',
              '            zero = nextZero;', '        }',
              '        QuoteMath.CostBounds memory result = M.cost(M.logSumExp(zero, one), 10e18);',
              f'        assert(result.lowerWad <= {lo} && result.upperWad >= {hi});',
              '        assert(result.upperWad - result.lowerWad <= 2 * (64 + 32 * 2562) * 10 + 2);',
              '    }', '}']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    destination = Path(__file__).resolve().parents[1] / 'contracts/test/FactoredLogFixtures.t.sol'
    destination.write_text(render(), encoding='utf-8')
    print('Verified tail inequality and generated 13 precision-stable interval fixtures.')
