"""Independent full-state and closed-form fixtures for Solidity graph elimination."""
from decimal import Decimal as D
from itertools import permutations
from pathlib import Path
from factored_log_fixtures import stable

U = 10**18


def liabilities(events, b, scopes, seed):
    liabilities = []
    for state in range(1 << events):
        total = 0
        for i, scope in enumerate(scopes):
            bits = [bit for bit in range(events) if scope & (1 << bit)]
            local = sum(((state >> event) & 1) << bit for bit, event in enumerate(bits))
            total += ((seed + i*7 + local*13) % 43) * b // 10
        liabilities.append(total)
    return liabilities


def cost(events, b, scopes, seed):
    return sum((D(q)/b).exp() for q in liabilities(events, b, scopes, seed)).ln() * b


def render():
    lines = ['// SPDX-License-Identifier: UNLICENSED', 'pragma solidity 0.8.28;',
             '// Generated by scripts/factored_cost_fixtures.py; do not edit.',
             'import {FactoredCost as F} from "../src/FactoredCost.sol";',
             'import {QuoteMath} from "../src/QuoteMath.sol";',
             'contract FactoredCostFixturesTest {']
    cases = [(3, b, [0, 1, 6, 5, 7], list(order), i+1)
             for i, order in enumerate(permutations(range(3)))
             for b in [10**12, 3*U+1, 10**27]]
    cases += [(4, 10*U, [3, 6, 12, 9], [0, 1, 2, 3], 9),
              (6, 10*U, [0, 5, 40], [5, 3, 1, 0, 2, 4], 7),
              (1, 10**12, [], [0], 0)]
    for i, (events, b, scopes, order, seed) in enumerate(cases):
        lo, hi = stable(lambda: cost(events, b, scopes, seed))
        maximum = max(liabilities(events, b, scopes, seed))
        lines += [f'    function test_graph_{i}() public pure {{',
                  f'        check({events}, {b}, hex"{"".join(f"{s:02x}" for s in scopes)}", '
                  f'hex"{"".join(f"{e:02x}" for e in order)}", {seed}, {lo}, {hi}, {maximum});', '    }']
    for width, count in [(1, 31), (2, 64)]:
        # Independent parity coordinates: width free initial bits; each later bit
        # is uniquely determined by its predecessor bits and that window's parity.
        counts = [sum(i % (32-width) == j for i in range(count)) for j in range(32-width)]
        lo, hi = stable(lambda: (D(2).ln()*width + sum((1+(D(n)/10).exp()).ln() for n in counts)) * 10*U)
        lines += [f'    function test_32_events_width_{width}() public pure {{',
                  f'        F.Factor[] memory factors = new F.Factor[]({count});',
                  f'        for (uint256 i; i < {count}; i++) {{',
                  f'            factors[i].scope = uint32({(1 << (width+1))-1}) << uint32(i % {32-width});',
                  f'            factors[i].values = new uint256[]({1 << (width+1)});',
                  f'            for (uint256 j; j < {1 << (width+1)}; j++) {{',
                  '                factors[i].values[j] = ((j ^ (j >> 1) ^ (j >> 2)) & 1) * 1e18;',
                  '            }', '        }',
                  '        uint8[] memory order = new uint8[](32);',
                  '        for (uint8 i; i < 32; i++) order[i] = i;',
                  f'        assert(F.validate(32, 10e18, factors, order) == {width});',
                  '        QuoteMath.CostBounds memory result = F.bounds(32, 10e18, factors, order);',
                  f'        assert(result.lowerWad <= {lo} && result.upperWad >= {hi});',
                  '        assert(result.upperWad - result.lowerWad <= 2 * (64 + 32 * 2562) * 10 + 2);',
                  f'        assert(F.maxLiability(32, 10e18, factors, order) == {count}e18);',
                  '    }']
    lines += ['    function check(uint8 events, uint256 b, bytes memory scopes, bytes memory permutation, uint256 seed, uint256 lo, uint256 hi, uint256 maximum) private pure {',
              '        F.Factor[] memory factors = new F.Factor[](scopes.length);',
              '        for (uint256 i; i < scopes.length; i++) {',
              '            uint32 scope = uint8(scopes[i]);',
              '            uint256 size;',
              '            for (uint32 s = scope; s != 0; s &= s - 1) size++;',
              '            factors[i].scope = scope;',
              '            factors[i].values = new uint256[](1 << size);',
              '            for (uint256 j; j < factors[i].values.length; j++) {',
              '                factors[i].values[j] = ((seed + i*7 + j*13) % 43) * b / 10;',
              '            }', '        }',
              '        uint8[] memory order = new uint8[](permutation.length);',
              '        for (uint256 i; i < order.length; i++) order[i] = uint8(permutation[i]);',
              '        QuoteMath.CostBounds memory result = F.bounds(events, b, factors, order);',
              '        assert(result.lowerWad <= lo && result.upperWad >= hi);',
              '        assert(F.maxLiability(events, b, factors, order) == maximum);',
              '    }', '}']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    destination = Path(__file__).resolve().parents[1] / 'contracts/test/FactoredCostFixtures.t.sol'
    destination.write_text(render(), encoding='utf-8')
    print('Generated 23 precision-stable factored graph fixtures.')
