"""Independent atomic quote checks, with stable 80/120-digit ideal prices."""
from decimal import Decimal as D
from pathlib import Path
from factored_log_fixtures import stable


def local_state(state, scope):
    events = [event for event in range(3) if scope & (1 << event)]
    return sum(((state >> event) & 1) << bit for bit, event in enumerate(events))


def render():
    lines = ['// SPDX-License-Identifier: UNLICENSED', 'pragma solidity 0.8.28;',
             '// Generated by scripts/factored_quote_fixtures.py; do not edit.',
             'import {FactoredQuote as Q} from "../src/FactoredQuote.sol";',
             'contract FactoredQuoteFixturesTest {']
    scopes = [0, 1, 6, 5, 7]
    trades = [(3, 8, True), (5, 14, True), (5, 14, False),
              (7, 85, True), (7, 85, False), (1, 2, False)]
    for decimals in [0, 6, 18]:
        unit = 10**decimals
        b, quantity = 100*unit, 10*unit
        before = [sum(20*unit + ((i*7 + local_state(state, scope)*13) % 43)*unit//10
                      for i, scope in enumerate(scopes)) for state in range(8)]
        for i, (scope, mask, is_buy) in enumerate(trades):
            after = [q + ((quantity if is_buy else -quantity) if mask & (1 << local_state(state, scope)) else 0)
                     for state, q in enumerate(before)]
            def ideal_price():
                def cost(q):
                    return D(b) * sum((D(v)/b).exp() for v in q).ln()
                return (cost(after)-cost(before)) * (1 if is_buy else -1)
            floor, ceil = stable(ideal_price)
            ideal = ceil if is_buy else floor
            assert ideal > 0
            lines += [f'    function test_quote_{decimals}_{i}() public pure {{',
                      f'        check({decimals}, {scope}, {mask}, {str(is_buy).lower()}, {ideal}, {max(after)});', '    }']
    lines += ['    function check(uint8 decimals, uint32 scope, uint256 mask, bool isBuy, uint256 ideal, uint256 maximum) private pure {',
              '        uint128 unit = uint128(10 ** uint256(decimals));',
              '        Q.Market memory m;',
              '        m.events = 3; m.decimals = decimals; m.liquidity = 100 * unit;',
              '        m.order = new uint8[](3); m.order[0] = 2; m.order[1] = 0; m.order[2] = 1;',
              '        m.factors = new Q.Factor[](5);',
              '        uint32[5] memory scopes = [uint32(0), 1, 6, 5, 7];',
              '        for (uint256 i; i < scopes.length; i++) {',
              '            uint256 size;',
              '            for (uint32 s = scopes[i]; s != 0; s &= s-1) size++;',
              '            m.factors[i].scope = scopes[i];',
              '            m.factors[i].values = new uint128[](1 << size);',
              '            for (uint256 j; j < m.factors[i].values.length; j++) {',
              '                m.factors[i].values[j] = 20 * unit + uint128((i*7 + j*13) % 43) * unit / 10;',
              '            }', '        }',
              '        Q.Quote memory result = isBuy ? Q.buy(m, scope, mask, 10*unit, 10*unit) : Q.sell(m, scope, mask, 10*unit, 1);',
              '        assert(result.maxLiabilityAfter == maximum);',
              '        uint256 numerator = 2 * uint256(m.liquidity) * 82048;',
              '        uint256 allowance = numerator / 1e18 + (numerator % 1e18 == 0 ? 0 : 1) + 3;',
              '        if (isBuy) assert(result.collateral >= ideal && result.collateral - ideal <= allowance);',
              '        else assert(result.collateral <= ideal && ideal - result.collateral <= allowance);',
              '    }', '}']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    destination = Path(__file__).resolve().parents[1] / 'contracts/test/FactoredQuoteFixtures.t.sol'
    destination.write_text(render(), encoding='utf-8')
    print('Generated 18 precision-stable factored quote fixtures.')
