"""Generate independent cost-enclosure tests, stable at 80 and 120 digits."""
from decimal import Decimal as D, ROUND_FLOOR, ROUND_CEILING, localcontext
from pathlib import Path
from reference_quotes import CASES


def bracket(b, q, precision):
    with localcontext() as ctx:
        ctx.prec = precision
        b = D(b)
        cost = b * sum((D(x) / b).exp() for x in q).ln()  # all values already WAD
        return int(cost.to_integral_value(rounding=ROUND_FLOOR)), int(cost.to_integral_value(rounding=ROUND_CEILING))


def cases():
    for name, _, b, q, mask, qty in CASES:
        b, q, qty = int(D(b)*10**18), [int(D(x)*10**18) for x in q], int(D(qty)*10**18)
        yield name + "_before", b, q
        yield name + "_after", b, [x + (qty if mask & (1 << i) else 0) for i, x in enumerate(q)]
    for b in (10**12, 10**27):
        for n in (2, 4, 8):
            yield f"uniform_{b}_{n}", b, [100*b]*n
            yield f"skew_{b}_{n}", b, [100*b] + [0]*(n-1)
    for gap in (1, 10**18-1, 10**18+1, 41*10**18, 42*10**18, 100*10**18):
        yield f"gap_{gap}", 10**18, [gap, 0, 1, gap-1]


def render():
    lines = ['// SPDX-License-Identifier: UNLICENSED', 'pragma solidity 0.8.28;',
             '// Generated by scripts/lmsr_cost_fixtures.py; do not edit.',
             'import {LmsrCost} from "../src/LmsrCost.sol";',
             'import {QuoteMath} from "../src/QuoteMath.sol";',
             'contract LmsrCostFixturesTest {']
    for name, b, q in cases():
        lo, hi = bracket(b, q, 80)
        assert (lo, hi) == bracket(b, q, 120), name
        values = ', '.join([f'uint256({q[0]})'] + [str(x) for x in q[1:]] + ['0']*(8-len(q)))
        lines += [f'    function test_{name}() public pure {{',
                  f'        check([{values}], {len(q)}, {b}, {lo}, {hi});', '    }']
    lines += ['    function check(uint256[8] memory values, uint256 n, uint256 b, uint256 lo, uint256 hi) private pure {',
              '        uint256[] memory q = new uint256[](n);',
              '        for (uint256 i; i < n; i++) q[i] = values[i];',
              '        QuoteMath.CostBounds memory bounds = LmsrCost.bounds(q, b);',
              '        assert(bounds.lowerWad <= lo && bounds.upperWad >= hi);',
              '    }', '}']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    (Path(__file__).resolve().parents[1] / 'contracts/test/LmsrCostFixtures.t.sol').write_text(render(), encoding='utf-8')
