"""Check full atomic-unit quotes against independent Decimal cost differences."""
from decimal import Decimal as D, ROUND_CEILING, ROUND_FLOOR, localcontext
from pathlib import Path
from reference_quotes import CASES


def ideal_quote(case, decimals, precision):
    _, _, b, q, mask, quantity = case
    with localcontext() as ctx:
        ctx.prec = precision
        b, q, quantity = D(b), list(map(D, q)), D(quantity)
        after = [x + (quantity if mask & (1 << i) else 0) for i, x in enumerate(q)]
        costs = [b * sum((x / b).exp() for x in state).ln() for state in (q, after)]
        rounding = ROUND_CEILING if quantity > 0 else ROUND_FLOOR
        return int((abs(costs[1] - costs[0]) * 10**decimals).to_integral_value(rounding=rounding))


def atoms(value, decimals):
    result = D(value) * 10**decimals
    assert result == result.to_integral_value(), "Fixture must use representable atomic amounts"
    return int(result)


def render():
    lines = ['// SPDX-License-Identifier: UNLICENSED', 'pragma solidity 0.8.28;',
             '// Generated by scripts/lmsr_quote_fixtures.py; do not edit.',
             'import {LmsrQuote} from "../src/LmsrQuote.sol";',
             'contract LmsrQuoteFixturesTest {']
    cases = [(c, 18 if c[0] == 'small_trade' else 6) for c in CASES]
    cases += [(CASES[0], 0), (CASES[0], 18)]
    for case, decimals in cases:
        name, _, b, q, mask, quantity = case
        expected = ideal_quote(case, decimals, 80)
        assert expected == ideal_quote(case, decimals, 120), name
        b_atoms, quantity_atoms = atoms(b, decimals), abs(atoms(quantity, decimals))
        factor = 10**(18-decimals)
        numerator = b_atoms * factor * (len(q)*512 + 256)
        error = (numerator + 10**18 - 1) // 10**18 + 1
        # Each endpoint can be 2*E away from truth: difference adds two endpoints.
        slack = (4*error + factor - 1) // factor + 1
        buy = D(quantity) > 0
        method, limit = ('buy', 'type(uint128).max') if buy else ('sell', '0')
        lines += [f'    function test_{name}_{decimals}() public pure {{',
                  f'        uint128[] memory q = new uint128[]({len(q)});']
        for i, value in enumerate(q):
            if D(value) != 0:
                lines.append(f'        q[{i}] = {atoms(value, decimals)};')
        lines += [f'        LmsrQuote.Market memory m = LmsrQuote.Market(q, {b_atoms}, {decimals});',
                  f'        LmsrQuote.Quote memory result = LmsrQuote.{method}(m, {mask}, {quantity_atoms}, {limit});']
        condition = f'result.collateral >= {expected} && result.collateral <= {expected} + {slack}' if buy else f'result.collateral <= {expected} && result.collateral + {slack} >= {expected}'
        lines += [f'        assert({condition});', '    }']
    return '\n'.join(lines + ['}']) + '\n'


if __name__ == '__main__':
    (Path(__file__).resolve().parents[1] / 'contracts/test/LmsrQuoteFixtures.t.sol').write_text(render(), encoding='utf-8')
