"""Generate Solidity rounding tests from the same scenarios as the Rust oracle.

These Decimal cost intervals are test data, not production exp/log error bounds.
Require identical integer brackets at 80 and 120 digits before writing fixtures.
"""
from decimal import Decimal as D, ROUND_CEILING, ROUND_FLOOR, localcontext
from pathlib import Path
from reference_quotes import CASES


def values(case, precision):
    name, _, b_text, q_text, mask, quantity_text = case
    with localcontext() as ctx:
        ctx.prec = precision
        b, quantity = D(b_text), D(quantity_text)
        before = list(map(D, q_text))
        after = [q + (quantity if mask & (1 << i) else 0) for i, q in enumerate(before)]
        costs = [b * sum((q / b).exp() for q in state).ln() for state in (before, after)]
        # One extra WAD unit of guard on each side of the Decimal approximation.
        bounds = [(int((c * D(10)**18).to_integral_value(rounding=ROUND_FLOOR)) - 1,
                   int((c * D(10)**18).to_integral_value(rounding=ROUND_CEILING)) + 1) for c in costs]
        rounding = ROUND_CEILING if quantity > 0 else ROUND_FLOOR
        ideal = [int((abs(costs[1] - costs[0]) * D(10)**d).to_integral_value(rounding=rounding)) for d in (0, 6, 18)]
        return name, quantity > 0, bounds, ideal


def render():
    lines = ['// SPDX-License-Identifier: UNLICENSED', 'pragma solidity 0.8.28;',
             '// Generated by scripts/quote_bounds_fixtures.py; do not edit.',
             'import {QuoteMath} from "../src/QuoteMath.sol";',
             'contract QuoteBoundsFixturesTest {']
    for case in CASES:
        result = values(case, 80)
        assert result == values(case, 120), f"Unstable Decimal brackets: {case[0]}"
        name, buy, (before, after), ideal = result
        lines.extend([f'    function testFixture_{name}() public pure {{',
                      f'        QuoteMath.CostBounds memory a = QuoteMath.CostBounds({before[0]}, {before[1]});',
                      f'        QuoteMath.CostBounds memory b = QuoteMath.CostBounds({after[0]}, {after[1]});'])
        for decimals, expected in zip((0, 6, 18), ideal):
            method = 'buyFromBounds' if buy else 'sellFromBounds'
            comparison = f'quote >= {expected} && quote <= {expected} + 4' if buy else f'quote <= {expected} && quote + 4 >= {expected}'
            lines.extend(['        {', f'            uint128 quote = QuoteMath.{method}(a, b, {decimals});',
                          f'            assert({comparison});', '        }'])
        lines.append('    }')
    lines.append('}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    target = Path(__file__).resolve().parents[1] / 'contracts/test/QuoteBoundsFixtures.t.sol'
    target.write_text(render(), encoding='utf-8')
