import { useEffect, useRef, useState } from 'react';
import { Link } from 'wouter';
import { formatUnits } from 'viem';
import { useAuth } from '../auth/context';
import { discoverWallets, type BrowserWallet } from '../auth/wallet-choice';
import { amount, walletKey, tradingWalletKey } from '../portfolio';
import { check, events, loadState, pendingKey, prepare, readPending, submit, atoms, type Action, type Pending, type Provider, type Review, type State } from '../kuru';
import './portfolio.css';
import './kuru.css';

const initial: Action = { kind: 'deposit', asset: 'cash', amount: '1', price: '0.45', minOut: '0.4', order: '' };
const labels: Record<Action['kind'], string> = { approve: 'Approve deposit', deposit: 'Deposit', withdraw: 'Withdraw', 'limit-buy': 'Limit buy', 'limit-sell': 'Limit sell', 'market-buy': 'Market buy', 'market-sell': 'Market sell', cancel: 'Cancel order' };
const message = (e: unknown) => e instanceof Error ? e.message : 'Request failed. Check your wallet before retrying.';
export default function Kuru({ onBusy, onConvert }: { onBusy(busy: boolean): void; onConvert(): void }) {
  const { controller, state: auth } = useAuth();
  const [wallets, setWallets] = useState<BrowserWallet[]>([]), [choice, setChoice] = useState('0');
  const [owner, setOwner] = useState(''), [state, setState] = useState<State | null>(null);
  const [action, setAction] = useState<Action>(initial), [review, setReview] = useState<Review | null>(null);
  const [pending, setPending] = useState<Pending | null>(null), [busy, setBusy] = useState(false), [storageError, setStorageError] = useState(false);
  const [notice, setNotice] = useState('Connect your trading wallet to see its Kuru balances and orders.');
  const [replacement, setReplacement] = useState(''), [ack, setAck] = useState(false);
  const [confirmedHash, setConfirmedHash] = useState('');
  const [conversion, setConversion] = useState(''), [fee, setFee] = useState('300'), [scan, setScan] = useState<any>(null);
  const provider = useRef<Provider | null>(null), cleanup = useRef<() => void>(() => {}), generation = useRef(0), working = useRef(false), live = useRef(true);
  const reviewRef = useRef(review); reviewRef.current = review;
  useEffect(() => { live.current = true; return () => { live.current = false; ++generation.current; cleanup.current(); }; }, []);
  useEffect(() => discoverWallets(w => setWallets(previous => previous.some(v => v.provider === w.provider) ? previous : [...previous, w])), []);
  useEffect(() => { const restore = () => { try { setPending(readPending(localStorage)); setStorageError(false); } catch (e) { setStorageError(true); setNotice(message(e)); } }; restore(); window.addEventListener('storage', restore); return () => window.removeEventListener('storage', restore); }, []);
  useEffect(() => { onBusy(busy || !!review || !!pending || storageError); return () => onBusy(false); }, [busy, review, pending, storageError, onBusy]);
  function save(p: Pending | null) { if (p) localStorage.setItem(pendingKey, JSON.stringify(p)); else localStorage.removeItem(pendingKey); if (live.current) setPending(p); }
  async function run(fn: () => Promise<void>) {
    if (working.current) return; working.current = true; setBusy(true);
    try { await fn(); } catch (e) { if (live.current) setNotice(message(e)); }
    finally { working.current = false; if (live.current) setBusy(false); }
  }
  async function refresh(before = '') { if (!owner) return; const version = generation.current; const data = await loadState(owner, before); if (live.current && generation.current === version) setState(data); }
  function edit(values: Partial<Action>) { ++generation.current; setReview(null); setAction(a => ({ ...a, ...values })); }
  async function connect() {
    cleanup.current(); ++generation.current; setReview(null); setOwner(''); setState(null);
    const version = generation.current;
    const p: Provider | undefined = wallets[Number(choice)]?.provider;
    if (!p) throw new Error('Install or open MetaMask, then reconnect.');
    const changed = () => { ++generation.current; setReview(null); setOwner(''); setState(null); setNotice('Wallet changed. Reconnect. Any submitted transaction remains in tracking.'); };
    for (const name of ['accountsChanged', 'chainChanged', 'disconnect']) p.on?.(name, changed);
    cleanup.current = () => { for (const name of ['accountsChanged', 'chainChanged', 'disconnect']) p.removeListener?.(name, changed); };
    const accounts = await p.request({ method: 'eth_requestAccounts' }) as string[];
    if (!Array.isArray(accounts) || !/^0x[0-9a-f]{40}$/i.test(accounts[0])) throw new Error('No wallet account returned.');
    const next = await loadState(accounts[0]);
    if (!live.current || version !== generation.current) throw new Error('Wallet changed during connection. Reconnect.');
    provider.current = p; setOwner(accounts[0].toLowerCase());
    if (auth.address) { try { sessionStorage.setItem(walletKey(auth.address), accounts[0].toLowerCase()); sessionStorage.setItem(tradingWalletKey(auth.address), accounts[0].toLowerCase()); } catch { /* Optional view preference. */ } }
    setState(next); setNotice('Wallet connected. Every action is reviewed and confirmed separately.');
  }
  async function reviewAction() {
    if (!provider.current || !owner || !auth.address) return;
    const version = generation.current;
    setReview(null); setNotice('Simulating your exact action...');
    const next = await prepare(provider.current, action, owner, auth.address);
    if (live.current && version === generation.current) { setReview(next); setNotice(next.action.kind === 'approve' && action.kind === 'deposit' ? 'This deposit needs token permission first. Confirm this exact approval, then review the deposit separately.' : 'Review the amounts and maximum network fee below.'); }
  }
  async function confirm() {
    const r = review, p = provider.current, version = generation.current;
    if (!r || !p || pending || storageError) return;
    if (!navigator.locks) throw new Error('This browser needs Web Locks support to protect wallet submissions.');
    await navigator.locks.request('flurbo-kuru-submit', { ifAvailable: true }, async lock => {
      if (!lock || readPending(localStorage)) throw new Error('A Kuru transaction is already being tracked.');
      try { await submit(p, r, save, () => live.current && version === generation.current && reviewRef.current === r && controller.getSnapshot().address === r.login); setNotice('Submitted. Check confirmation before another action.'); }
      finally { setReview(null); }
    });
  }
  async function confirmation() {
    const saved = readPending(localStorage); if (!saved || !provider.current) throw new Error('Connect a wallet to check the saved transaction.');
    const status = await check(provider.current, saved);
    const current = readPending(localStorage);
    if (current?.hash !== saved.hash || current?.started !== saved.started) throw new Error('Tracking changed in another tab.');
    if (status === 'confirmed' || status === 'reverted') {
      setConfirmedHash(saved.hash!);
      save(null); setReview(null);
      if (status === 'confirmed' && saved.review.action.kind === 'approve') setAction({ ...saved.review.action, kind: 'deposit' });
      setNotice(status === 'confirmed' ? `${labels[saved.review.action.kind]} confirmed. The transaction and matching contract event were verified. Refresh balances for current funds.` : 'Transaction reverted. No successful action was confirmed. Review again.');
      await refresh();
    } else setNotice(status === 'pending' ? 'Transaction is still pending. Do not submit it again.' : 'Waiting for a second canonical confirmation.');
  }
  const disabled = busy || !!pending || storageError;
  const activity = state && owner ? events(state.activity.logs, state.contracts.market, owner).reverse() : [];
  return <div className="portfolio-view kuru-view">
    <section className="kuru-intro"><span className="eyebrow">H YES / AUSD · Kuru</span><h2>A place for your <em>single view.</em></h2><p>Trade H YES receipts on the order book. Combined claims continue to trade with Flurbo’s shared pool.</p><p>Test assets and synthetic operator liquidity. <Link href="/account" onClick={e => { if (disabled || review) e.preventDefault(); else onConvert(); }}>Convert H YES holdings to receipts in Explore & trade.</Link></p></section>
    <section className="portfolio-wallet"><div><label htmlFor="kuru-wallet">Trading wallet</label><select id="kuru-wallet" disabled={busy || !!review} value={choice} onChange={e => { setChoice(e.target.value); setOwner(''); setState(null); ++generation.current; cleanup.current(); provider.current = null; }}>{wallets.map((w, i) => <option value={i} key={i}>{w.name}</option>)}</select></div><button className="button button-dark" disabled={busy || !!review} onClick={() => void run(connect)}>Connect MetaMask</button>{owner && <p className="portfolio-address">Trading as {owner}. Your Mera login stays separate.</p>}</section>
    <p role="status" className="kuru-notice">{notice}</p>
    {confirmedHash && <p className="portfolio-footnote"><a href={`https://testnet.monadscan.com/tx/${confirmedHash}`} target="_blank" rel="noreferrer">View the last checked transaction receipt</a></p>}
    {storageError && <section className="kuru-card"><h3>Saved tracking needs attention.</h3><p>Signing is blocked because the saved transaction record could not be read. Check wallet activity before removing it. This does not cancel a transaction.</p><label className="kuru-checkbox"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)}/>I checked wallet activity and understand the risk of submitting twice.</label><button className="button button-outline" disabled={busy || !ack} onClick={() => void run(async () => { save(null); setStorageError(false); setAck(false); })}>Remove unreadable tracking</button></section>}
    {state && <div className="kuru-book"><div><span>Best bid</span><strong>{state.kuru.best_bid_wad ? formatUnits(BigInt(state.kuru.best_bid_wad), 18) : 'No bid'} <small>AUSD</small></strong></div><div><span>Best ask</span><strong>{state.kuru.best_ask_wad ? formatUnits(BigInt(state.kuru.best_ask_wad), 18) : 'No ask'} <small>AUSD</small></strong></div><p>Indicative top of book. Review simulates your full quantity, fees and minimum received.</p></div>}
    {state && <><div className="portfolio-toolbar"><p className="portfolio-freshness">Observed at block {state.snapshot.block_number.toLocaleString()}. Refresh to check current balances.</p><button className="button button-outline" disabled={busy} onClick={() => void run(() => refresh())}>Refresh</button></div><section className="portfolio-metrics">{[['Wallet AUSD', state.wallet.ausd_atoms], ['Wallet H YES receipts', state.wallet.receipt_atoms], ['Available Kuru AUSD', state.wallet.margin_available_ausd_atoms], ['Available Kuru receipts', state.wallet.margin_available_receipt_atoms]].map(([label, value]) => <article key={label}><strong>{amount(value)}</strong><p>{label}</p></article>)}</section><p className="portfolio-footnote">Available balances exclude funds reserved for open orders. Cancellation releases only the unfilled remainder. Withdraw moves available funds back to this same wallet.</p></>}
    {pending && <section className="kuru-card" aria-label="Transaction tracking"><h3>Finish your pending action.</h3><p>{labels[pending.review.action.kind]} for {pending.review.owner}</p>{pending.hash && <a className="portfolio-address" href={`https://testnet.monadscan.com/tx/${pending.hash}`} target="_blank" rel="noreferrer">View transaction {pending.hash.slice(0, 12)}...</a>}<label htmlFor="kuru-replacement">Transaction hash from wallet activity (including a replacement)</label><input id="kuru-replacement" value={replacement} disabled={busy} onChange={e => setReplacement(e.target.value)}/><div className="kuru-actions"><button className="button button-outline" disabled={busy} onClick={() => void run(async () => { if (!/^0x[0-9a-f]{64}$/i.test(replacement)) throw new Error('Enter a full transaction hash.'); save({ ...pending, hash: replacement.toLowerCase() }); })}>Attach hash</button><button className="button button-dark" disabled={busy || !provider.current} onClick={() => void run(confirmation)}>Check confirmation</button></div><details><summary>Resolve tracking manually</summary><p>Only clear this after checking wallet activity. Clearing does not cancel a transaction or stop an open wallet prompt.</p><label className="kuru-checkbox"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)}/>I checked the wallet and understand duplicate submission can spend again.</label><button className="button button-outline" disabled={busy || !ack} onClick={() => { save(null); setAck(false); setNotice('Tracking cleared. Check balances before preparing another action.'); }}>Clear tracking</button></details></section>}
    <div className="kuru-grid"><section className="kuru-card"><span className="eyebrow">Your next move</span><h3>Choose an action.</h3><fieldset disabled={disabled}><label htmlFor="kuru-action">Action</label><select id="kuru-action" value={action.kind} onChange={e => edit({ kind: e.target.value as Action['kind'] })}>{Object.entries(labels).map(([k, label]) => <option key={k} value={k}>{label}</option>)}</select>{['approve', 'deposit', 'withdraw'].includes(action.kind) && <><label htmlFor="kuru-asset">Asset</label><select id="kuru-asset" value={action.asset} onChange={e => edit({ asset: e.target.value as Action['asset'] })}><option value="cash">AUSD</option><option value="receipt">H YES receipt</option></select><p>Approve the exact deposit amount first, then review Deposit separately. Withdrawing needs no token approval.</p></>}{action.kind === 'cancel' ? <><label htmlFor="kuru-order">Order ID</label><input id="kuru-order" value={action.order} onChange={e => edit({ order: e.target.value })}/></> : <><label htmlFor="kuru-amount">{action.kind === 'market-buy' ? 'AUSD to spend' : action.kind.includes('buy') || action.kind.includes('sell') ? 'H YES receipts' : 'Amount'}</label><input id="kuru-amount" inputMode="decimal" value={action.amount} onChange={e => edit({ amount: e.target.value })}/></>}{action.kind.startsWith('limit-') && <><label htmlFor="kuru-price">Limit price per receipt (AUSD)</label><input id="kuru-price" inputMode="decimal" value={action.price} onChange={e => edit({ price: e.target.value })}/><p>Post-only: crosses the spread? The order reverts instead of taking liquidity. Price step 0.0001; size step 0.01.</p></>}{action.kind.startsWith('market-') && <><label htmlFor="kuru-min">Minimum received after fees ({action.kind === 'market-buy' ? 'H YES receipts' : 'AUSD'})</label><input id="kuru-min" inputMode="decimal" value={action.minOut} onChange={e => edit({ minOut: e.target.value })}/><p>Uses your available Kuru balance. Fill-or-kill; the transaction reverts if full execution or your minimum cannot be met. Taker fee 0.30%. Proceeds stay in Kuru.</p></>}<button className="button button-dark" disabled={!owner} onClick={() => void run(reviewAction)}>{busy ? 'Checking...' : `Review ${labels[action.kind].toLowerCase()}`}</button></fieldset></section>
    <section className="kuru-card kuru-review"><span className="eyebrow">Review & confirm</span><h3>{review ? labels[review.action.kind] : 'Every move, considered.'}</h3>{review ? <><p>Wallet {review.owner}</p><dl><dt>Amount / order</dt><dd>{review.action.kind === 'cancel' ? '#' + review.action.order : review.action.amount + (review.action.kind === 'market-buy' || ['approve', 'deposit', 'withdraw'].includes(review.action.kind) && review.action.asset === 'cash' ? ' AUSD' : ' H YES receipts')}</dd>{review.action.kind.startsWith('limit-') && <><dt>Limit price</dt><dd>{review.action.price} AUSD</dd></>}{review.netOut && <><dt>Simulated received after fees</dt><dd>{amount(review.netOut)}</dd><dt>Minimum received</dt><dd>{review.action.minOut}</dd></>}<dt>Maximum network fee</dt><dd>{(Number(BigInt(review.gas) * BigInt(review.gasPrice)) / 1e18).toFixed(6)} MON</dd><dt>Review expires</dt><dd>{new Date(review.expires).toLocaleTimeString()}</dd></dl><p>State is checked again before the wallet prompt. Limits remain in force if confirmation takes longer. A posted limit order stays open until filled or cancelled.</p><div className="kuru-actions"><button className="button button-lime" disabled={disabled} onClick={() => void run(confirm)}>Confirm in wallet</button><button className="button button-outline" disabled={busy} onClick={() => setReview(null)}>Back</button></div></> : <p>Choose an action to check funding and simulate it. Approval only grants permission; it does not deposit funds or place an order.</p>}</section></div>
    {state && <><div className="portfolio-section-heading"><h2>Your open orders.</h2></div><div className="portfolio-table"><table><caption>Regular orders from IDs {Math.max(1, Number(state.orders_page.through_id) - 19)} to {state.orders_page.through_id}. Other pages may contain more orders.</caption><thead><tr><th>Order</th><th>Side</th><th>Price (AUSD)</th><th>Remaining receipts</th><th/></tr></thead><tbody>{state.orders.map(o => <tr key={o.id}><td>#{o.id}</td><td>{o.side}</td><td>{amount(o.price_units)}</td><td>{amount(o.remaining_atoms)}</td><td><button className="button button-outline" disabled={disabled} onClick={() => { edit({ kind: 'cancel', order: o.id }); document.getElementById('kuru-action')?.focus(); }}>Cancel...</button></td></tr>)}{!state.orders.length && <tr><td colSpan={5}>No open regular orders owned by this wallet on this page.</td></tr>}</tbody></table></div><div className="portfolio-pagination"><button className="button button-outline" disabled={busy} onClick={() => void run(() => refresh())}>Newest orders</button><button className="button button-outline" disabled={busy || !state.orders_page.next_before} onClick={() => void run(() => refresh(state.orders_page.next_before!))}>Older orders</button></div><div className="portfolio-section-heading"><h2>Recent Kuru activity.</h2></div><div className="portfolio-table"><table><caption>On-chain events in blocks {state.activity.from_block} to {state.activity.to_block}. This is a bounded recent view, not complete history.</caption><thead><tr><th>Action</th><th>Order</th><th>Filled / remaining receipts</th><th>Transaction</th></tr></thead><tbody>{activity.map((e, i) => <tr key={i}><td>{e.name === 'Trade' ? 'Fill' : e.name === 'OrderCreated' ? 'Order posted' : 'Order cancelled'}</td><td>#{String(e.args.orderId)}</td><td>{e.name === 'Trade' ? `${amount(String(e.args.filledSize))} / ${amount(String(e.args.updatedSize))}` : amount(String(e.args.size))}</td><td><a href={`https://testnet.monadscan.com/tx/${e.hash}`} target="_blank" rel="noreferrer">View receipt</a></td></tr>)}{!activity.length && <tr><td colSpan={4}>No matching events in this block window.</td></tr>}</tbody></table></div><p className="portfolio-footnote">Fill sizes are before taker fees. Wallet balances, available margin and open-order reserves are separate. Maker rebate: 0.10% of the received asset, subject to contract rounding.</p></>}
    <details className="kuru-card"><summary>Compare the pool and order book</summary><p>Read-only arbitrage research for the deployed executor. Enter a hypothetical MON/AUSD conversion for gas accounting. Test assets have no asserted market value. Nothing here submits a trade.</p><label htmlFor="kuru-conversion">Hypothetical AUSD per MON</label><input id="kuru-conversion" value={conversion} inputMode="decimal" onChange={e => { setConversion(e.target.value); setScan(null); }}/><label htmlFor="kuru-fee">Maximum gas price (gwei)</label><input id="kuru-fee" value={fee} inputMode="numeric" onChange={e => { setFee(e.target.value); setScan(null); }}/><button className="button button-outline" disabled={busy} onClick={() => void run(async () => { setScan(null); if (!/^[1-9][0-9]{0,2}$/.test(fee) || Number(fee) > 500) throw new Error('Gas cap must be 1 to 500 gwei.'); const response = await fetch('/api/kuru-scan?' + new URLSearchParams({ conversion: atoms(conversion).toString(), fee: (BigInt(fee) * 1000000000n).toString() }), { signal: AbortSignal.timeout(50000) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Scan unavailable'); setScan(data); })}>Run comparison</button>{scan && <><p>{scan.status === 'expired' ? 'Expired comparison. ' : 'Comparison only. '}Snapshot block {scan.block_number}. Nothing here is an executable quote.</p>{scan.candidates.map((c: any, i: number) => <p key={i}>{c.direction === 'pool_to_kuru' ? 'Pool to Kuru' : 'Kuru to pool'}: {c.status === 'rejected' ? c.reason : `${amount(String(c.net_after_allowance_atoms))} AUSD simulated surplus after venue fees and reserved gas. No execution.`}</p>)}</>}</details>
  </div>;
}
